import type { Metadata } from "next";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { getMessages } from "next-intl/server";
import Providers from "@/components/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <Providers locale={locale} messages={messages}>
      <Header />
      {children}
      <Footer className="pt-[50px] pb-[160px] md:pt-[160px] md:pb-[50px]" />
    </Providers>
  );
}
